version: '3'

services:
  app:
    container_name: forum
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-forum
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      NODE_ENV: development
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: pnpm start
    volumes:
      - .:/home/node/forum
      - /home/node/forum/node_modules
    networks:
      - forum-connect

  postgres-forum:
    container_name: postgres-forum
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-forum-data:/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    networks:
      - forum-connect

volumes:
  postgres-forum-data:

networks:
  forum-connect:
      driver: bridge