version: '3'

services:
  app:
    container_name: forum
    restart: on-failure
    build: .
    depends_on:
      - postgres-forum
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      NODE_ENV: development
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: pnpm start
    volumes:
      - .:/home/node/forum
      - /home/node/forum/node_modules
    networks:
      - forum-connect

  postgres-forum:
    container_name: postgres-forum
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-forum-data:/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - forum-connect

volumes:
  postgres-forum-data:

networks:
  forum-connect:
      driver: bridge